version: 0.2

phases:
  pre_build:
    commands:
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 778203996491.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - pwd
      - ls
      - docker build -t node:latest .
      - docker tag node:latest 778203996491.dkr.ecr.us-east-1.amazonaws.com/node:latest
  post_build:
    commands:
      - docker push 778203996491.dkr.ecr.us-east-1.amazonaws.com/node:latest
      - printf '[{"name":node,"imageUri":"778203996491.dkr.ecr.us-east-1.amazonaws.com/node:latest"}]' > imagedefinitions.json
      - ls
      - cat imagedefinitions.json
artifacts:
  files: imagedefinitions.json